language: java
jdk:
 - oraclejdk8
script: 
  - ant build
  - ant jar

after_success:
  - ls bin/
  - ls -l bin/jar

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: bin/jar/TowerDefence2D.jar
  skip_cleanup: true
  on:
    tags: true